name: phi-3-training-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - pip:
      - torch~=2.0
      - torchvision~=0.18
      - trl==0.8.6
      - transformers~=4.41
      - datasets~=2.19
      - azureml-core~=1.30
      - azure-storage-blob==12.19
      - azure-ai-ml~=1.16
      - azure-identity~=1.16
      - accelerate~=0.30
      - mlflow==2.14.1
      - azureml-mlflow==1.56.0 
